version: 3

tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  run:
    ignore_error: true
    cmds:
      - docker compose down
      - docker rmi elite-clinic-rest-api_api
      - docker-compose up --build

  migrate-create:
    cmds:
      - migrate create -ext sql -dir ./migrations -seq {{.CLI_ARGS}}

  sqlc:
    cmds:
      - sqlc generate