// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: appointments.sql

package db

import (
	"context"
	"time"
)

const getAppointment = `-- name: GetAppointment :one
SELECT id, comment, patientid, doctorid FROM appointments WHERE id = $1  LIMIT 1
`

func (q *Queries) GetAppointment(ctx context.Context, id time.Time) (*Appointment, error) {
	row := q.db.QueryRowContext(ctx, getAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.Comment,
		&i.Patientid,
		&i.Doctorid,
	)
	return &i, err
}
