// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Appointment struct {
	ID        time.Time      `json:"id"`
	Comment   sql.NullString `json:"comment"`
	PatientID string         `json:"patient_id"`
	DoctorID  uuid.UUID      `json:"doctor_id"`
}
