// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	GetAppointment(ctx context.Context, id time.Time) (*Appointment, error)
}

var _ Querier = (*Queries)(nil)
